### ISSUE TITLE
Can import same mnemonic into different accounts by changing Name or Keypair or Networks

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tf-wallet-connector-extension#11]
I was able to import the same mnemonic into two different accounts by only changing the key pair type.
![image](https://github.com/threefoldtech/tf-wallet-connector-extension/assets/109473873/a7568e3d-d13e-4a3b-8f22-afde536ef478)

Then I was able to import the same mnemonic again with the same key pair type and the same everything except that the name is different.
![image](https://github.com/threefoldtech/tf-wallet-connector-extension/assets/109473873/3501536a-7864-4e92-b7fa-cb11544f16bc)

And the same thing could happen when selecting different networks.

**Comment by maayarosama** [comment]
no
